# verbose
#/control/verbose 2
#/run/verbose 2
#/tracking/verbose 0

# change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 6

# Geometry setups
#
/LINAC/Geometry/SetIsocenter            100. cm
/LINAC/Geometry/SetJaw1XAperture       -5. cm
/LINAC/Geometry/SetJaw2XAperture        5. cm
/LINAC/Geometry/SetJaw1YAperture       -5. cm
/LINAC/Geometry/SetJaw2YAperture        5. cm
/LINAC/Geometry/SetPhantomXDim          30. cm
/LINAC/Geometry/SetPhantomYDim          30. cm
/LINAC/Geometry/SetPhantomZDim          30. cm
/LINAC/Geometry/SetNumberOfVoxelsAlongX 10
/LINAC/Geometry/SetNumberOfVoxelsAlongY 10
/LINAC/Geometry/SetNumberOfVoxelsAlongZ 10

# initialize kernel
/run/initialize

# run
/run/printProgress 100000
/run/beamOn 10000000
